[package]
name = "invidious-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"]}
serde_json = { version = "1" }
url = { version = "2.5" }
async-trait = { version = "0.1" }
reqwest = { version = "*", features = ["json"]}
