use super::attachments;
use super::common;
use serde::{Deserialize, Serialize};

// type structure are referenced from:
// https://docs.invidious.io/api/channels_endpoint/#get-apiv1channelsidcommunity

/*
* ChannelId response
{
    "author": String,
    "authorId": String,
    "authorUrl": String,
    "authorVerified": Boolean,
    "authorBanners": [
        // One or more ImageObject
    ],
    "authorThumbnails": [
        // One or more ImageObject
    ],

    "subCount": Number, // Integer
    "totalViews": Number, // Integer
    "joined": Number, // Unix timestamp

    "autoGenerated": Boolean,
    "isFamilyFriendly": Boolean,

    "description": String,
    "descriptionHtml": String,
    "allowedRegions": String[],

    "tabs": String[],

    "latestVideos": [
        // One or more VideoObject
    ],
    "relatedChannels": [
        // One or more ChannelObject
    ]
}
*/
#[derive(Debug, Clone, Eq, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ChannelInfo {
    pub author: String,
    pub author_id: String,
    pub author_url: String,
    pub author_verified: bool,
    pub author_banners: Vec<common::ImageObject>,
    pub author_thumbnails: Vec<common::ImageObject>,

    pub sub_count: i64,
    pub total_views: i64,
    pub joined: i64,

    pub auto_generated: bool,
    pub is_family_friendly: bool,

    pub description: String,
    pub description_html: String,
    pub allowed_regions: Vec<String>,

    pub tabs: Vec<String>,
    pub tags: Vec<String>,

    pub latest_videos: Vec<common::VideoObject>,
    pub related_channels: Vec<common::ChannelObject>,
}

/*
RelatedChannels
{
    "relatedChannels": [
        // One or more ChannelObject
    ],
    "continuation": String
}
*/
#[derive(Debug, Clone, Eq, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RelatedChannels {
    related_channels: Vec<common::ChannelObject>,
    continuation: String,
}

/*
* ChannelPlaylist
{
    "playlists": [
        // One or more PlaylistOject
    ],
    "continuation": continuation
}
*/

#[derive(Debug, Clone, Eq, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ChannelPlaylist {
    playlists: Vec<common::PlaylistObject>,
    continuation: String,
}

/*
ChannelVideos
{
    "videos": [
        // One or more VideoObject
    ],
    "continuation": String
}
*/
#[derive(Debug, Clone, Eq, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ChannelVideos {
    videos: Vec<common::VideoObject>,
    continuation: String,
}

/*
CommunityComments
    {
        "attachment": ImageAttachment | MultiImageAttachment | VideoAttachment | PollAttachment | PlaylistAttachment
        "author": String,
        "authorIsChannelOwner": Boolean
        "authorId": String,
        "authorThumbnails": ImageObject[],
        "authorUrl": String,
        "commentId": String,
        "content": String,
        "contentHtml": String,
        "isEdited": Boolean,
        "likeCount": Number,
        "published": Number,
        "publishedText": String,
        "replyCount": Number
    }
*/
#[derive(Debug, Clone, Eq, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CommunityComment {
    attachment: attachments::Attachment,
    author: String,
    author_is_channel_owner: bool,
    author_id: String,
    author_thumbnails: Vec<common::ImageObject>,
    author_url: String,
    comment_id: String,
    content: String,
    content_html: String,
    is_edited: bool,
    like_count: i64,
    published: i64,
    published_text: String,
    reply_count: i64,
}

/*
ChannelCommunity
{
    "authorId": String,
    "comments": {
        "attachment": ImageAttachment | MultiImageAttachment | VideoAttachment | PollAttachment | PlaylistAttachment
        "author": String,
        "authorIsChannelOwner": Boolean
        "authorId": String,
        "authorThumbnails": ImageObject[],
        "authorUrl": String,
        "commentId": String,
        "content": String,
        "contentHtml": String,
        "isEdited": Boolean,
        "likeCount": Number,
        "published": Number,
        "publishedText": String,
        "replyCount": Number
    }[]
}
*/
#[derive(Debug, Clone, Eq, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ChannelCommunity {
    author: String,
    commonts: Vec<CommunityComment>,
}

/*
{
    type: "channel",
    author: String,
    authorId: String,
    authorUrl: String,

    authorThumbnails: [
      {
        url: String,
        width: Int32,
        height: Int32
      }
    ],
    autoGenerated: Bool
    subCount: Int32,
    videoCount: Int32,
    description: String,
    descriptionHtml: String
  }
*/
#[derive(Debug, Clone, Eq, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SearchChannelUnit {
    #[serde(rename = "type")]
    pub o_type: String,
    pub author: String,
    pub author_id: String,
    pub author_url: String,
}
